# Generated by Django 3.1.7 on 2021-11-24 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='delivery',
            field=models.CharField(blank=True, max_length=222, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='payment',
            field=models.CharField(blank=True, max_length=222, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='duration',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='payment_range',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='remote',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
    ]
