# Generated by Django 3.1.7 on 2021-11-25 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20211124_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='available',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='field',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
