# Generated by Django 3.1.7 on 2021-11-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20211124_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('application', 'Application'), ('message', 'Message')], max_length=25),
        ),
    ]
