# Generated by Django 3.1.7 on 2021-11-25 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20211124_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
